main: fr.pederobien.uhc.UHCPlugin
name: UHCPlugin
version: 1.0
api-version: 1.13

description:
commands:
  loadconf:
    description:
    permission: UHCPlugin.loadconf
  pausegame:
    description:
    permission: UHCPlugin.pausegame
  startgame:
    description:
    permission: UHCPlugin.startgame
  stopgame:
    description:
    permission: UHCPlugin.stopgame
  spawnsave:
    description:
    permission: UHCPlugin.savespawn
  spawnlist:
    description:
    permission: UHCPlugin.spawnlist
  spawnlaunch:
    description:
    permission: UHCPlugin.spawnload
  spawnremove:
    description:
    permission: UHCPlugin.spawnremove
  teamrandom:
    description:
    permission: UHCPlugin.teamrandom
  teamcreate:
    description:
    permission: UHCPlugin.teamcreate
  teamremoveall:
    description:
    permission: UHCPlugin.teamremoveall