main: fr.martinfimbel.switchuhc.SwitchUHCPlugin
name: SwitchUHCPlugin
version: 1.0
api-version: 1.13

description:
commands:
  pausegame:
    description:
    permission: SwitchUHCPlugin.pausegame
  startgame:
    description:
    permission: SwitchUHCPlugin.startgame
  stopgame:
    description:
    permission: SwitchUHCPlugin.stopgame
  hg:
    description:
    permission: SwitchUHCPlugin.hg
  spawn:
    description:
    permission: SwitchUHCPlugin.spawn
  bd:
    description:
    permission: SwitchUHCPlugin.bd
  base:
    description:
    permission: SwitchUHCPlugin.base
  sw:
    description:
    permission: SwitchUHCPlugin.sw