main: fr.pederobien.uhc.UHCPlugin
name: UHCPlugin
version: 1.0
api-version: 1.13

description:
commands:
  pausegame:
    description:
    permission: UHCPlugin.pausegame
  startgame:
    description:
    permission: UHCPlugin.startgame
  stopgame:
    description:
    permission: UHCPlugin.stopgame
  teamrandom:
    description:
    permission: UHCPlugin.teamrandom
  teamcreate:
    description:
    permission: UHCPlugin.teamcreate
  teamremoveall:
    description:
    permission: UHCPlugin.teamremoveall
  hg:
    description:
    permission: UHCPlugin.hg
  spawn:
    description:
    permission: UHCPlugin.spawn
  bd:
    description:
    permission: UHCPlugin.bd
  base:
    description:
    permission: UHCPlugin.base